{
    "name": "NFU Sale Order Batch Packaging",
    "summary": "Add minimum and maximum order quantities to sale orders and batches and use default packaging",
    "author": "BAKEUP",
    "website": "https://www.bakeup.org",
    "category": "Sale",
    "version": "16.0.1.4.0",
    "depends": ["sale", "sale_order_batch"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_config_parameter.xml",
        "data/uom_data.xml",
        "wizard/sale_order_batch_packaging_fill_views.xml",
        "views/uom_uom_views.xml",
        "views/sale_order_views.xml",
        "views/sale_order_batch_views.xml",
        "views/sale_order_batch_product_views.xml",
    ],
    "license": "LGPL-3",
    "post_init_hook": "post_init_hook",
}
